docs: Adding comment about file inclusion in TS section
developit/microbundle pull request #888
Opened 2021-09-03 07:26 UTC by rschristian

Closes #807

When building with TypeScript, [we provide a default value for `"files"`](https://github.com/developit/microbundle/blob/b1a637486234a2ae784ccf0c512321e2d3efef7c/src/index.js#L533) which has the side effect of altering what files are included for compilation with Microbundle. While this is intentional (see #621) it isn't exactly obvious to users why files included when using `tsc` are suddenly not included when using Microbundle.

2021-09-03 07:37 UTC, AndyOGo requested changes
Thanks a lot for clarification!

I would explicitly mention that ts configs like typeRoots wont work.

2021-09-03 07:39 UTC, rschristian commented
@AndyOGo Hm, that's not a Microbundle thing. TSC wouldn't do anything differently. That's just not what that `typeRoots` is for.

2021-09-03 07:46 UTC, AndyOGo commented
Thanks for your answer.

I have custum definition files, which I usually add by using typeRoots. And it works stable with tsc.

Though with microbundle it wont work.

My guess is because the default includes is **/*, but if files is specified then includes default is an empty array.
I could be wrong though.

2021-09-03 07:51 UTC, rschristian commented
@AndyOGo 

It's exactly that, yeah. By default `include` covers everything, so `tsc` will include those ambient declarations. As Microbundle needs to alter what's included, you as the user need to specify.

Though I should say `typeRoots` isn't actually doing anything for you in that repo you provided. Ambient declarations will be picked up so long as they're included by `files` or `include`. You don't need `typeRoots` there are all. It has no effect.

2021-10-06 14:05 UTC, developit approved these changes

2021-10-06 14:05 UTC, merged